spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: transport
  task:
    scheduling:
      pool:
        size: 1
app:
  task:
    expire_after_seconds: 8
server:
  port: 8888
